export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
// export const INCREASE_PRICE = 'INCREASE_PRICE';
// export const DECREASE_PRICE = 'DECREASE_PRICE';
